// dsh-driftwatch — human-readable and machine-readable reports.
import type { DriftReport, SessionFingerprint } from './drift.js'

const VERDICT_BADGE: Record<DriftReport['verdict'], string> = {
  stable: '🟢 stable',
  moderate: '🟡 moderate drift',
  significant: '🔴 significant drift',
}

function ms(value: number): string {
  if (value < 1000) return `${value} ms`
  if (value < 60_000) return `${(value / 1000).toFixed(1)} s`
  const min = Math.floor(value / 60_000)
  const sec = Math.round((value % 60_000) / 1000)
  return `${min}m ${sec}s`
}

function signed(value: number): string {
  return value > 0 ? `+${value}` : String(value)
}

function pctLabel(p: number | null): string {
  if (p === null) return '—'
  const rounded = Math.round(p)
  const mark = Math.abs(rounded) >= 20 ? ' ⚠️' : ''
  return `${rounded > 0 ? '+' : ''}${rounded}%${mark}`
}

/** Render the drift report as Markdown (for humans, PR comments, logs). */
export function renderMarkdown(report: DriftReport, a: SessionFingerprint, b: SessionFingerprint): string {
  const lines: string[] = []
  lines.push(`# Behavior drift report`)
  lines.push('')
  lines.push(`**Verdict: ${VERDICT_BADGE[report.verdict]}** — score ${report.score}/100`)
  lines.push('')
  lines.push(`| | A (baseline) | B (candidate) |`)
  lines.push(`|---|---|---|`)
  lines.push(`| session | \`${report.a.id}\` | \`${report.b.id}\` |`)
  lines.push(`| turns | ${report.a.turns} | ${report.b.turns} |`)
  lines.push(`| records | ${report.a.records} | ${report.b.records} |`)
  lines.push(`| tool calls | ${report.a.toolCalls} | ${report.b.toolCalls} |`)
  lines.push(`| duration | ${ms(report.a.durationMs)} | ${ms(report.b.durationMs)} |`)
  lines.push('')

  lines.push(`## Tool sequence`)
  const q = report.toolSequence
  lines.push(`${q.exact ? 'LCS alignment' : 'multiset overlap (sequences too long for exact LCS)'}: ` +
    `**${q.kept}** kept, **${q.removed}** removed, **${q.added}** added — divergence ${(q.divergence * 100).toFixed(1)}%`)
  if (report.toolNamesOnlyInA.length) lines.push(`- Only in A: ${report.toolNamesOnlyInA.map((n) => `\`${n}\``).join(', ')}`)
  if (report.toolNamesOnlyInB.length) lines.push(`- Only in B: ${report.toolNamesOnlyInB.map((n) => `\`${n}\``).join(', ')}`)
  lines.push('')

  if (report.toolUsage.length) {
    lines.push(`## Tool usage changes`)
    lines.push('')
    lines.push(`| tool | A | B | Δ |`)
    lines.push(`|---|---:|---:|---:|`)
    for (const t of report.toolUsage.slice(0, 15)) {
      lines.push(`| \`${t.name}\` | ${t.a} | ${t.b} | ${signed(t.delta)} |`)
    }
    lines.push('')
  }

  lines.push(`## Metric changes`)
  lines.push('')
  lines.push(`| metric | A | B | Δ | change |`)
  lines.push(`|---|---:|---:|---:|---:|`)
  for (const m of report.metrics) {
    if (m.a === 0 && m.b === 0) continue
    lines.push(`| ${m.name} | ${m.a} | ${m.b} | ${signed(m.delta)} | ${pctLabel(m.pct)} |`)
  }
  lines.push('')

  const f = report.files
  if (f.onlyInA.length || f.onlyInB.length) {
    lines.push(`## File operations`)
    if (f.onlyInA.length) lines.push(`- **Only touched in A** (${f.onlyInA.length}): ${f.onlyInA.slice(0, 10).map((p) => `\`${p}\``).join(', ')}${f.onlyInA.length > 10 ? ' …' : ''}`)
    if (f.onlyInB.length) lines.push(`- **Only touched in B** (${f.onlyInB.length}): ${f.onlyInB.slice(0, 10).map((p) => `\`${p}\``).join(', ')}${f.onlyInB.length > 10 ? ' …' : ''}`)
    lines.push(`- Common: ${f.common.length}`)
    lines.push('')
  }

  if (report.verdict !== 'stable') {
    lines.push(`## What changed most`)
    const top: string[] = []
    if (report.toolSequence.divergence > 0.2) top.push(`tool sequence ordered differently (${(report.toolSequence.divergence * 100).toFixed(0)}% not on the common subsequence)`)
    const hist = report.toolUsage.slice(0, 3).filter((t) => Math.abs(t.delta) > 0)
    if (hist.length) top.push(`tool mix: ${hist.map((t) => `\`${t.name}\` ${signed(t.delta)}`).join(', ')}`)
    const bigMetrics = report.metrics.filter((m) => m.pct !== null && Math.abs(m.pct) >= 20)
    if (bigMetrics.length) top.push(`metrics: ${bigMetrics.map((m) => `${m.name} ${pctLabel(m.pct)}`).join(', ')}`)
    if (f.onlyInA.length || f.onlyInB.length) top.push(`file targets: ${f.onlyInA.length} dropped, ${f.onlyInB.length} new`)
    for (const t of top) lines.push(`- ${t}`)
    lines.push('')
    lines.push(`> DriftWatch does not judge whether this drift is acceptable — that is your call.`)
    lines.push('')
  }

  lines.push(`---`)
  lines.push(`_Generated by dsh-driftwatch at ${report.generatedAt}_`)
  return lines.join('\n')
}

/** Render a compact single-line summary (for CLI stdout when not verbose). */
export function renderSummary(report: DriftReport): string {
  return `drift ${report.score}/100 (${report.verdict}) — tools ${report.a.toolCalls}→${report.b.toolCalls}, ` +
    `sequence divergence ${(report.toolSequence.divergence * 100).toFixed(1)}%, ` +
    `duration ${ms(report.a.durationMs)}→${ms(report.b.durationMs)}`
}

/** Render a fingerprint as Markdown (for `fingerprint` command). */
export function renderFingerprint(fp: SessionFingerprint): string {
  const lines: string[] = []
  lines.push(`# Session fingerprint`)
  lines.push('')
  lines.push(`- id: \`${fp.id}\``)
  lines.push(`- path: \`${fp.path}\``)
  if (fp.workspace) lines.push(`- workspace: \`${fp.workspace}\``)
  lines.push(`- records: ${fp.records} | turns: ${fp.turns} | steps: ${fp.steps}`)
  lines.push(`- duration: ${ms(fp.durationMs)}`)
  lines.push(`- tool calls: ${fp.toolCalls.length} (errors: ${fp.toolErrors}, max per turn: ${fp.maxToolsPerTurn})`)
  lines.push(`- reasoning: ${fp.reasoningChunks} chunks / ${fp.reasoningChars} chars`)
  lines.push(`- retries: ${fp.retries} | compactions: ${fp.compactions}`)
  const reasons = Object.entries(fp.completionReasons).map(([k, v]) => `${k}×${v}`).join(', ')
  if (reasons) lines.push(`- turn outcomes: ${reasons}`)
  lines.push('')
  lines.push(`## Tools`)
  lines.push('')
  const entries = Object.entries(fp.toolHistogram).sort((x, y) => y[1] - x[1]).slice(0, 25)
  for (const [name, count] of entries) lines.push(`- \`${name}\`: ${count}`)
  if (fp.fileOps.length) {
    const unique = [...new Set(fp.fileOps.map((f) => f.path))]
    lines.push('')
    lines.push(`## Files touched (${unique.length})`)
    for (const p of unique.slice(0, 25)) lines.push(`- \`${p}\``)
  }
  return lines.join('\n')
}
